server:
  port: 2025

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_details
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.bytecode.provider: org.hibernate.dialect.MySQL80InnoDBDialect
      hibernate.format_sql:

springdoc:
  api-docs:
    path: /api-docs

banner:
  location: classpath:banner.txt
